=== dongfangding/JavaDemo/src/main/java/jdk/XML/schema/expReturn.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/expReturn"
	xmlns:tns="http://www.example.org/expReturn" elementFormDefault="qualified">

	<!-- 创建根元素 -->
	<xsd:element name="Root" type="tns:rootType"/>
	
	<!-- 创建根元素类型 -->
	<xsd:complexType name="rootType">
		<xsd:sequence>
			<xsd:element name="Header" type="tns:headerType" />
			<xsd:element name="Body" type="tns:bodyType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- 创建Header元素类型 -->
	<xsd:complexType name="headerType">
		<xsd:sequence>
			<xsd:element name="MessageReferenceNumber" type="xsd:string"/>
			<xsd:element name="DocumentName" type="tns:documentNameType"/>
			<xsd:element name="SenderCode" type="tns:senderCodeType"/>
			<xsd:element name="ReceiverCode" type="tns:receiverCodeType"/>
			<xsd:element name="MessageSendingDateTime" type="tns:dateType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- 创建Body元素类型 -->
	<xsd:complexType name="bodyType">
		<xsd:sequence>
			<xsd:element name="Shipment" type="tns:shipmentType" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- 创建Shipment元素类型 -->
	<xsd:complexType name="shipmentType">
		<xsd:sequence>
			<xsd:element name="shipmentID" type="tns:idType"/>
			<xsd:element name="rtnReason" type="xsd:string" />
			<xsd:element name="pickupRtnFlag" type="tns:pickcoFlagType"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<!-- 规定DocumentName的值为固定值 -->
	<xsd:simpleType name="documentNameType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="E_EXP_RTN" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- 规定SenderCode的值 -->
	<xsd:simpleType name="senderCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="AMAZON" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- 规定 ReceiverCode-->
	<xsd:simpleType name="receiverCodeType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="YANWEN" />
			<xsd:enumeration value="EASTTOP" />
			<xsd:enumeration value="SINOTRANS" />
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- 创建日期的验证格式，必须yyyy-MM-dd HH:mm:ss -->
	<xsd:simpleType name="dateType">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="[1-9][0-9]{3}[-]((([0][13578])|([1][02]))[-](([0][1-9])|([12][0-9])|([3][01]))|(([0][469])|([1][1]))[-](([0][1-9])|([12][0-9])|([3][0]))|([0][2])[-](([0][1-9])|([12][0-9])))[ ]((([01][0-9])|([2][0-3]))[:][0-5][0-9][:][0-5][0-9])"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- 创建packageID和shipmentID规则 -->
	<xsd:simpleType name="idType">
		<xsd:restriction base="xsd:string">
			<xsd:maxLength value="32"/>
		</xsd:restriction>
	</xsd:simpleType>
	
	<!-- 创建pickupRtnFlag元素类型 -->
	<xsd:simpleType name="pickcoFlagType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Y" />
			<xsd:enumeration value="N" />
		</xsd:restriction>
	</xsd:simpleType>
	
</xsd:schema>

=== dongfangding/JavaDemo/src/main/java/jdk/XML/schema/expReturn.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- 如果需要代码提示和xml验证，必须引入如下Root中的所有属性，用来指定命名空间和schemaLocation -->
<!-- 如果是网上schema，提供一下信息，即可验证。如果是本地schema。需要在eclipse的配置中，
	window```Preference````XML````XML Catalog中添加本地schema路径 -->
<!-- xsi:schemaLocation="http://www.example.org/expReturn  
		http://172.20.33.51/AEC/schema/express/expReturn.xsd " -->
<Root xmlns="http://www.example.org/expReturn" 
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:noNamespaceSchemaLocation="expReturn.xsd"
		>
	<Header>
		<MessageReferenceNumber>快递订单退货</MessageReferenceNumber>
		<DocumentName>E_EXP_RTN</DocumentName>
		<SenderCode>AMAZON</SenderCode>
		<ReceiverCode>SINOTRANS</ReceiverCode>
		<MessageSendingDateTime>2016-09-23 16:00:01</MessageSendingDateTime>
	</Header>
	
	<Body>
		<Shipment>
			<shipmentID>EX201609230001</shipmentID>
			<rtnReason>库内异常</rtnReason>
			<pickupRtnFlag>Y</pickupRtnFlag>
		</Shipment>
		<Shipment>
			<shipmentID>EX201609230002</shipmentID>
			<rtnReason>seller取消单</rtnReason>
			<pickupRtnFlag>N</pickupRtnFlag>
		</Shipment>
	</Body>
</Root>
