=== dongfangding/JavaDemo/src/main/java/jdk/XML/schema/teacher.dtd
<?xml version="1.0" encoding="UTF-8"?>
        <!--?代表0次或1次， * 代表0次或多次， +至少出现一次-->
        <!ELEMENT teacher (teaName, teaSex, teaEmail, teaTel, teaAddress, teaBorn, students)>
        <!ATTLIST teacher id ID #REQUIRED>
        <!ELEMENT teaName (#PCDATA)>
        <!ELEMENT teaSex (#PCDATA)>
        <!ELEMENT teaEmail (#PCDATA)>
        <!ELEMENT teaTel (#PCDATA)>
        <!ELEMENT teaAddress (#PCDATA)>
        <!ELEMENT teaBorn (#PCDATA)>
        <!ELEMENT students (student*)>
        <!ELEMENT student (stuName,stuTel,stuEmail)>
        <!ELEMENT stuName (#PCDATA)>
        <!ELEMENT stuTel (#PCDATA)>
        <!ELEMENT stuEmail (#PCDATA)>

=== dongfangding/JavaDemo/src/main/java/jdk/XML/schema/teacherDtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- 引入的固定写法 !DOCTYPE后跟根节点 -->
<!DOCTYPE teacher SYSTEM "teacher.dtd">
<teacher id = "t1">
	<teaName>ddf</teaName>
	<teaSex>男</teaSex>
	<teaEmail>ddf@qq.com</teaEmail>
	<teaTel>12200</teaTel>
	<teaAddress>上海市</teaAddress>
	<teaBorn>1970-12-23</teaBorn>
	<students>
		<student>
			<stuName>zhangsan</stuName>
			<stuTel>120</stuTel>
			<stuEmail>zhangsan@qq.com</stuEmail>
		</student>
	</students>
</teacher>
